// Tutorial demo data — preloaded so first-time visitors can run the full
// pipeline in a single click without supplying their own FASTQ.
//
// The bundled FASTQ at /sample-data/sample_1k.fastq is the same synthetic
// fixture used by the byte-for-byte parity test in packages/core. It contains
// 1,000 reads generated by packages/core/test/fixtures/generate.py with the
// primers below. Running the pipeline against it should produce ~900 unique
// peptides in the results table.

import type { RoundForm } from "@/state/useRunStore";

// Synthetic primers — see packages/core/test/fixtures/generate.py for the
// generator that produced the bundled FASTQ. R0 and R1 differ by 1 bp in the
// barcode anchor; rv is identical (typical for cDNA-display libraries).
const R0_FW = "GTCAATGCCTAGAGGCTCAGATCG";
const R1_FW = "GTCAATGCCTAGAGGCTCAGATTG";
const RV = "GCATCGATCGATCGATCGATTG";
// Reverse-complement of RV for embedding into the reference sequence.
const RC_RV = "CAATCGATCGATCGATCGATGC";

// A synthetic reference that contains both rounds' Fw primers followed by
// the RC of the Rv primer. The preview step's anchor-search logic finds
// each round's anchor and the corresponding distance to Rv — both rounds
// produce ok-full status.
export const DEMO_REFERENCE =
  "NNNNN" +
  R0_FW +
  "AAAGGCCCCATCGGCCAAAGGCCCCATCGGCAATTAATTGGCCAATTGGCC" + // 51 bp filler
  RC_RV +
  "NNNNNNNNNN" +
  R1_FW +
  "AAAGGCCCCATCGGCCAAAGGCCCCATCGGCAATTAATTGGCCAATTGGCC" +
  RC_RV +
  "NNNNN";

export const DEMO_ROUNDS: ReadonlyArray<Omit<RoundForm, "id">> = [
  {
    name: "Round_0",
    fwPrimer: R0_FW,
    rvPrimer: RV,
    cdsStart: 1,
    cdsEnd: 57,
  },
  {
    name: "Round_1",
    fwPrimer: R1_FW,
    rvPrimer: RV,
    cdsStart: 1,
    cdsEnd: 54,
  },
];

export const DEMO_FASTQ_URL = "/sample-data/sample_1k.fastq";
export const DEMO_FASTQ_NAME = "sample_1k.fastq";

/** Fetch the bundled FASTQ and wrap it in a browser File object so the
 *  existing LocalFastqSource adapter can consume it without modification. */
export async function loadDemoFastq(): Promise<File> {
  const res = await fetch(DEMO_FASTQ_URL);
  if (!res.ok) {
    throw new Error(
      `Failed to load demo FASTQ from ${DEMO_FASTQ_URL}: HTTP ${res.status}`,
    );
  }
  const blob = await res.blob();
  // File extends Blob; the worker constructs a stream from .stream(), so
  // any File-shaped object works.
  return new File([blob], DEMO_FASTQ_NAME, { type: "application/octet-stream" });
}
